export const GET_BLOGS = "GET_BLOGS"
export const USER_NEW_SIGN_IN = "USER_NEW_SIGN_IN"
export const USER_CHECK_LOGGED_IN = "USER_CHECK_LOGGED_IN"
export const USER_GET_INFO = "USER_GET_INFO"
export const USER_LOG_OUT = "USER_LOG_OUT"
export const ADD_NEW_BLOG = "ADD_NEW_BLOG"